/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'surface-container-highest': '#e2e2e2',
        'on-tertiary-container': '#ef875e',
        'surface-container': '#eeeeee',
        primary: '#002155',
        'on-primary-container': '#7fa1f2',
        'on-primary-fixed': '#001945',
        error: '#ba1a1a',
        'surface-dim': '#dadada',
        'on-surface': '#1a1c1c',
        'on-tertiary-fixed': '#380d00',
        'surface-container-high': '#e8e8e8',
        'secondary-container': '#ff5722',
        'primary-fixed': '#d9e2ff',
        'primary-fixed-dim': '#b0c6ff',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#ffb5a0',
        'inverse-surface': '#2f3131',
        'tertiary-fixed-dim': '#ffb59a',
        'tertiary-container': '#692101',
        'surface-variant': '#e2e2e2',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'on-secondary-container': '#541100',
        'on-primary-fixed-variant': '#1a438e',
        'on-tertiary-fixed-variant': '#7b2e0d',
        'tertiary-fixed': '#ffdbcf',
        'on-surface-variant': '#434651',
        'on-tertiary': '#ffffff',
        secondary: '#b02f00',
        'surface-tint': '#375ca8',
        'inverse-on-surface': '#f1f1f1',
        'on-secondary-fixed': '#3b0900',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'on-background': '#1a1c1c',
        surface: '#f9f9f9',
        'surface-bright': '#f9f9f9',
        tertiary: '#451200',
        'secondary-fixed': '#ffdbd1',
        'primary-container': '#003580',
        'surface-container-low': '#f3f3f3',
        'on-secondary-fixed-variant': '#862200',
        'outline-variant': '#c4c6d3',
        outline: '#747782',
        'inverse-primary': '#b0c6ff',
        background: '#f9f9f9',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        lg: '24px',
        base: '8px',
        'container-max': '1280px',
        sm: '8px',
        md: '16px',
        xl: '32px',
        xxl: '48px',
        xs: '4px',
      },
      fontFamily: {
        display: ['Plus Jakarta Sans', 'sans-serif'],
        heading: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '56px', letterSpacing: '0', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        premium: '0 12px 32px -18px rgba(0, 53, 128, 0.35)',
        soft: '0 10px 30px -18px rgba(0, 53, 128, 0.28)',
      },
    },
  },
  plugins: [],
};
